### PR TITLE
Clean up source file headers

### PR DESCRIPTION
**Pull request by Bastian-Krause**
- add `SPDX-FileCopyrightText` to file headers
- drop redundant license headers
- clean up and drop redundant metadata from file headers

### CODE REVIEW

**Comment by Bastian-Krause** [comment]
Force-pushed:
- readded `@file` to all .c files, doxygen ignores those files otherwise

**Review by ejoerns — APPROVED** [review]
Looks fine from my side.

**Review by Raphexion — COMMENTED** [review]
For consistency, maybe we should update all www.prevas.com to www.prevas.dk. Because we have written Prevas *A/S* as the company name - which is the Danish branch. Moreover, it was developed in Denmark.

What do you think @prevas-lkmi

**Comment by prevas-lkmi** [comment]
@Raphexion thats ok, to use the prevas.com

**Review by prevas-lkmi — APPROVED** [review]
LGTM

**Pull request merged**
