### PR TITLE
rauc-hawkbit-updater: support available locales

### PR DESCRIPTION
**Pull request by Bastian-Krause**
This makes it possible to specify host names containing unicode character in the "hawkbit_server" config option if the system supports it.

Otherwise setting "hawkbit_server" to hüseldösel.de fails with (having CURLOPT_VERBOSE enabled):

```
* Failed to convert hüseldösel.de to ACE; could not convert string to UTF-8
* Closing connection -1
WARNING: Scheduled check for new software failed: URL using bad/illegal format or missing URL (3)
```

### CODE REVIEW

**Comment by Bastian-Krause** [comment]
Force-pushed:
- require locale's encoding to be UTF-8
- add test case for insufficient locale

**Comment by jluebbe** [comment]
Does this add a new requirement to have a UTF-8 locale shipped with the system (they can be quite large)? Or is this required already for other reasons?

**Comment by Bastian-Krause** [comment]
@jluebbe Yes, this introduces a requirement for UTF-8 locales. Do you have a suggestion how to handle this differently?

**Comment by Bastian-Krause** [comment]
We discussed this internally: UTF-8 locales can be quite large. We do not want to enforce that. PR #99 describes how to handle unicode characters in host names instead.

**Pull request closed without merging**
