### PR TITLE
Move to GitHub actions for testing

### PR DESCRIPTION
**Pull request by ejoerns**
This adds a simple workflow for performing the tests we did with Travis before. Travis introduced time budgets, even for open source projects, which makes GH actions even more attractive now (beyond the better capabilities and integration in the GH API).

This also fixes pkg-config check for libsystemd which was discovered to be unprecise during testing.

### CODE REVIEW

**Review by Bastian-Krause — APPROVED** [review]
Thanks! Doing authenticated Docker Hub requests will avoid issues like this in the future:

https://travis-ci.com/github/rauc/rauc-hawkbit-updater/jobs/463596059

**Comment by ejoerns** [comment]
Note that Travis credits for the 'rauc' organization are exhausted.
No further test jobs will run.
So we should merge this quickly!

**Comment by ejoerns** [comment]
@prevas-lkmi Thanks for merging and a Happy New Year to you!

I've now enabled branch protection for 'master' so that it requires the (new) tests to succeed before allowing to merge (can still be forced by project admins if required).

**Comment by prevas-lkmi** [comment]
@ejoerns Thanks and Happy New Year to you.

I'm sorry for not being more active in this project. I hope to get some more time this year. 
I really appreciate the work @Bastian-Krause and you are doing. Fixing bugs and cleaning up my shitty code :smiley:

**Comment by ejoerns** [comment]
@prevas-lkmi picking this up; would it be ok for you if I merge some of the cleanup stuff when having reviewed it? There is so much more about to come that I would like to pick the low hanging fruits in order to pave the way for new features and other enhancements of this project :smirk:

**Comment by prevas-lkmi** [comment]
@ejoerns No problem. You are more than welcome to just merge stuff, when you have reviewed it. I'm sorry for being such a showstopper :-)

**Comment by ejoerns** [comment]
@prevas-lkmi No problem, I just wanted to ensure it does not feel like I am taking over your project ;)

**Pull request merged**
