### PR TITLE
Add line to service script

### PR DESCRIPTION
**Pull request by tristengamingsupport**

### CODE REVIEW

**Comment by tristengamingsupport** [comment]
Sorry I goofed, wanted to merge into my own fork :sweat_smile:

**Comment by Bastian-Krause** [comment]
Note that there is no Exec= in the [Service] section (see `man 5 systemd.service`)

**Comment by ejoerns** [comment]
@tristengamingsupport `ExecStartPre=` is probably what you are looking for ;)

**Comment by tristengamingsupport** [comment]
Didn't know that could change depending on the group, thanks! @Bastian-Krause @ejoerns

**Pull request closed without merging**
